name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Só faz deploy se for na branch main

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}     # IP do servidor
          username: ${{ secrets.SERVER_USER }} # Usuário do servidor
          key: ${{ secrets.SERVER_KEY }}       # Chave SSH
          script: |
            cd /home/projeto-dino
            git pull origin main
            docker-compose up -d --build