name: Dino CI/CD

# 1. QUANDO o robô acorda?
on:
  push:
    branches: [ "main" ] # Sempre que você subir algo na main

# 2. O QUE o robô faz?
jobs:
  testar-dino:
    runs-on: ubuntu-latest # Ele liga um computador Linux na nuvem

    steps:
      - name: Pegando o código do Gustavo
        uses: actions/checkout@v4

      - name: Instalando o Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalando as dependências
        run: |
          pip install -r requirements.txt

      - name: Verificando se o código está quebrado
        run: python -m py_compile app/main.py